---
- name : facts & when
  hosts : Client1
  become : true

  tasks : 
  - name : remove
    yum : 
     name : httpd
     state : absent
    when : 
     - ansible_distribution == "CentOS"

  - name : install
    yum : 
     name : wget
     state : present
    when : 
     - ansible_apparmor.status == "disabled"
