---
- name : when with operator
  hosts : Client1
  become : true

  tasks : 
  - name : Install while condition met
    yum : 
     name : mariadb
     state : absent
    when : 
     - (ansible_distribution == "CentOS" and ansible_distribution_version == "7.9") 

  - name : remove while condition met
    yum : 
     name : mariadb
     state : present
    when : 
     - (ansible_hostname == "anode1" and ansible_machine == "x86_64")
...
