---
- name : facts
  hosts : Client1
  become : true
 
  tasks : 
  - name : remove
    yum : 
     name : httpd
     state : absent
    when : 
     - (ansible_distribution == "CentOS" and ansible_distribution_major_version >=7) 
       or 
       (ansible_distribution_file_variety == "RedHat" and ansible_distribution_version == "7.*")
