---
- name : Tomcat setup
  hosts : Client1
  become : true 

  tasks : 
  - name : install java
    yum : 
      name : java
      state : latest

  - name : Create destination directory
    file :
      path : /opt/tomcat
      state : directory

  - name : download tomcat
    get_url : 
     url : https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.tar.gz
     dest : /opt/tomcat/

  - name : Untar file
    unarchive : 
       src : /opt/tomcat/apache-tomcat-9.0.63.tar.gz
       dest : /opt/tomcat
       remote_src : yes

  - name : Start Service
    shell : nohup /opt/tomcat/apache-tomcat-9.0.63/bin/startup.sh
...
