---
- name : Tomcat setup using file variable
  hosts : Client1
  become : true
  vars_files : 
   - var_file

  tasks : 

  - name : Install java
    yum :
      name : java
      state : latest

  - name : create directory  
    file : 
     path : /opt/tomcat
     state : directory

  - name : download
    get_url : 
       url : "{{ download_url }}"
       dest : /opt/tomcat

  - name : untar
    unarchive : 
      src : /opt/tomcat/{{ file_name }}.tar.gz
      dest : /opt/tomcat
      remote_src : yes

  - name : start service
    shell : nohup /opt/tomcat/{{ file_name }}/bin/startup.sh
...
  
