---
- name : when example
  hosts : Client1
  become : true
  gather_facts : yes

  tasks : 
  - name : validate host
    command : hostname -s
    register : host_details
    when : ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  - debug : 
      var : host_details
...

