---
- name : with_items
  hosts : Client2
  become : true
  
  tasks : 
  - name : loop
    yum : 
     name : "{{ item }}"
     state : latest
    with_items :
     - wget
     - httpd
     - nginx
     - curl
