---
  - name : Create user
    user : 
     name : tomcat
     create_home : yes
     shell : /bin/bash
     comment : tomcat user
     uid : 0921
     state : present

  - name : Change permission
    file :
     path : /opt/tomcat
     mode : 755
     owner : tomcat
     recurse : yes
